default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: postgres
  password: juju2001
  host: localhost

development:
  <<: *default
  database: store_v2_development

test:
  <<: *default
  database: store_v2_test

production:
  <<: *default
  database: store_v2_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
